spring:
  security:
    oauth2:
      client:
        registration:
          crypto-portfolio:
            client-id: crypto-portfolio
            client-secret: secret
            client-name: Crypto Portfolio
            scope: user_info
            redirect-uri: http://localhost:8080/login/oauth2/code/crypto-portfolio
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            provider: crypto-provider
        provider:
          crypto-provider:
            token-uri: http://localhost:8081/auth/oauth/token
            authorization-uri: http://localhost:8081/auth/oauth/authorize
            user-info-uri: http://localhost:8081/auth/userinfo
            user-name-attribute: username
logging:
  level:
    root: INFO
    com.memorynotfound: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO